name: Deploy RSS feed

on:
  # Runs on all pushes
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Run every hour at 22 minutes past the hour.  22 was selected randomly to
  # avoid bunching work at any particular time.
  schedule:
    - cron: '22 * * * *'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run
# in-progress and latest queued.  However, do NOT cancel in-progress runs as we
# want to allow these production deployments to complete.
#
# This was included in the GitHub Pages template action, and I see no reason to
# change it.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build RSS page
        run: |
          mkdir -p output
          curl --user-agent "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" https://petition.parliament.uk/petitions.json\?state=recent | jq -r -f rss.jq > output/petitions.rss
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: output
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v4
